abacura/mud/session.py
abacura/plugins/commands/global.py
abacura/plugins/commands/pycharm.py
abacura/plugins/plugin.py

Added @action function does not handle plaintext vs color yet
Added @@ command to evaluate expressions
Added pycharm debug plugin which dynamically loads the pycharm debug module and connects to a remote host/port

Action Function Basic Implementation

---

abacura/plugins/__init__.py
abacura/plugins/commands/global.py
abacura/plugins/plugin.py

Working towards removing the need for the PluginHander 
Plugin inspect itself so that it can track actions, etc
Removed ticker annotation, working towards dynamic trigger creation

Allow for dynamic creation of actions, removed ticker annotation

---

abacura/mud/session.py
abacura/plugins/__init__.py
abacura/plugins/commands/global.py
abacura/plugins/plugin.py

remove app, loader from Plugin context
added msdp to Plugin context

Moved @session and @connect commands into Session

---

abacura/config.py
abacura/mud/session.py
abacura/plugins/__init__.py
abacura/plugins/aliases/manager.py
abacura/plugins/commands/global.py
abacura/plugins/plugin.py

Moved helper commands to separate plugins
Inject AliasManager into Plugin context
PEP-8 fixes

Refactored so that Config and AliasManager are not plugins

---

abacura/abacura.py
abacura/config.py
abacura/mud/session.py
abacura/plugins/commands/helper.py
abacura/plugins/debug/pycharm.py
abacura/plugins/loader.py
abacura/plugins/session/helper.py
abacura/utils/pycharm.py
abacura/utils/ring_buffer.py

Support for -d option to connect to remote debugger at startup
Handle case where spec is null when loading plugins

Push output messages into ring log (if configured)

---

abacura/plugins/__init__.py
abacura/plugins/loader.py

Added output() helper to Plugin

Removed textlog (tl) and sessions dict from PluginLoader

---

abacura-core/abacura/mud/session.py
abacura-core/abacura/plugins/__init__.py
abacura-core/abacura/plugins/director.py
abacura-core/abacura/plugins/events/__init__.py
abacura-core/abacura/plugins/events/events.py
abacura-core/abacura/plugins/loader.py
abacura-core/abacura/widgets/footer.py

Plugins register their events with register_object 
Removed event registration code from PluginLoader

EventManager is now instantiated by director  to support plugin reloading

---

abacura-core/abacura/plugins/__init__.py
abacura-core/abacura/plugins/demo/demo.py
abacura-core/abacura/plugins/loader.py
abacura-core/abacura/plugins/session/helper.py
abacura-kallisti/abacura_kallisti/plugins/scripts/script.py

Implemented plugin reloading with #reload and optionally auto reloading

---

abacura-core/abacura/plugins/__init__.py
abacura-core/abacura/plugins/commands/__init__.py
abacura-core/abacura/plugins/commands/helper.py
abacura-core/abacura/plugins/debug/pycharm.py
abacura-core/abacura/plugins/demo/demo.py
abacura-core/abacura/plugins/events/events.py
abacura-kallisti/abacura_kallisti/atlas/navigator.py
abacura-kallisti/abacura_kallisti/plugins/atlas/world.py
abacura-kallisti/abacura_kallisti/plugins/lok.py
abacura-kallisti/abacura_kallisti/plugins/scripts/script.py
abacura-kallisti/abacura_kallisti/screens.py

Improved display of a few commands #room, #event, #area Removed #lok demo command
Removed PTAM demo actions

Fixed simplified path display using itertools.groupby, improved command displays

---

abacura-core/abacura/plugins/loader.py
abacura-kallisti/abacura_kallisti/atlas/room.py
abacura-kallisti/abacura_kallisti/atlas/world.py
abacura-kallisti/abacura_kallisti/plugins/atlas/atlas_helper.py
abacura-kallisti/abacura_kallisti/plugins/atlas/room_watcher.py

Added #exits command
Send message when RoomWatcher sees a room
Show warning if saved room exits (world) don't match msdp exits
Ignore error when a plugin is renamed and we try and reload

 Added #exits command

---

abacura-core/abacura/plugins/commands/__init__.py
abacura-core/abacura/plugins/debug/profile.py
abacura-kallisti/abacura_kallisti/atlas/navigator.py
abacura-kallisti/abacura_kallisti/atlas/room.py
abacura-kallisti/abacura_kallisti/atlas/world.py
abacura-kallisti/abacura_kallisti/plugins/atlas/atlas_helper.py
abacura-kallisti/abacura_kallisti/plugins/navigate.py

Moved Room, Exit from world to room module

Added support for per argument help using docstring in commands

---

abacura-kallisti/abacura_kallisti/plugins/lokcomms.py

Usage is: #commslog <channel/speaker> <name arg> <on/off>
toggles output to comms window on or off

First pass at toggling comms window output for channel/speaker

---

abacura-core/abacura/mud/options/msdp.py
abacura-core/abacura/mud/session.py
abacura-core/abacura/plugins/__init__.py
abacura-core/abacura/plugins/debug/pycharm.py
abacura-kallisti/abacura_kallisti/plugins/async_navigate.py
abacura-kallisti/abacura_kallisti/plugins/atlas/location_helper.py
abacura-kallisti/abacura_kallisti/plugins/atlas/navigation_helper.py
abacura-kallisti/abacura_kallisti/plugins/atlas/world_helper.py
abacura-kallisti/abacura_kallisti/plugins/exec/ExecHelper.py
abacura-kallisti/abacura_kallisti/plugins/lok.py
abacura-kallisti/abacura_kallisti/plugins/scripts/navigate.py

echo on new line if last line doesn't end with a > (prompt) 
added #sql command to query the world db
added Plugin.send() method which defaults to an orange1 color for the echo
Don't echo account name, password

session.send() echoes to the textlog by default

---

abacura-core/abacura/plugins/commands/__init__.py
abacura-core/abacura/plugins/commands/helper.py
abacura-core/abacura/plugins/debug/profile.py
abacura-core/abacura/plugins/debug/pycharm.py
abacura-core/abacura/plugins/session/helper.py
abacura-kallisti/abacura_kallisti/atlas/world.py
abacura-kallisti/abacura_kallisti/plugins/async_navigate.py
abacura-kallisti/abacura_kallisti/plugins/atlas/world_helper.py

Added --commands option to #exit to allow setting commands for an exit
Added --door option to #exits to set name of a door

Updated #plugin to show details about specific plugins, improved #exits

---

abacura-core/abacura/plugins/__init__.py
abacura-core/abacura/plugins/aliases/helper.py
abacura-core/abacura/plugins/commands/__init__.py
abacura-core/abacura/plugins/debug/profile.py
abacura-core/abacura/plugins/demo/demo.py
abacura-core/abacura/plugins/session/helper.py
abacura-core/abacura/plugins/tickers/helper.py
abacura-kallisti/abacura_kallisti/atlas/navigator.py
abacura-kallisti/abacura_kallisti/atlas/room.py
abacura-kallisti/abacura_kallisti/mud/area.py
abacura-kallisti/abacura_kallisti/plugins/__init__.py
abacura-kallisti/abacura_kallisti/plugins/atlas/location_helper.py
abacura-kallisti/abacura_kallisti/plugins/atlas/navigation_helper.py
abacura-kallisti/abacura_kallisti/plugins/atlas/tour_helper.py
abacura-kallisti/abacura_kallisti/plugins/atlas/world_helper.py
abacura-kallisti/abacura_kallisti/plugins/lokcomms.py
abacura-kallisti/abacura_kallisti/plugins/scripts/navigate.py
abacura-kallisti/abacura_kallisti/plugins/scripts/tour_demo.py
abacura-kallisti/abacura_kallisti/plugins/scripts/tourguide.py

Added some navigation methods in preparation for routing
Moved command generation from Step into Exit so we can get commands without a NavigationPath / Step

Added #tour , TourGuide to do a tour (lap) within an area according to the .toml file specs

---

abacura-core/abacura/plugins/loader.py
abacura-core/abacura/plugins/session/helper.py
abacura-kallisti/abacura_kallisti/plugins/corpse.py

Show failed plugins in #plugin command
#reload retries failed packages

#reload retries failed plugins / packages

---

abacura-core/abacura/abacura.py
abacura-core/abacura/mud/session.py
abacura-core/abacura/plugins/__init__.py
abacura-core/abacura/plugins/loader.py
abacura-core/abacura/screens/__init__.py
abacura-core/abacura/widgets/footer.py
abacura-core/setup.py
abacura-kallisti/abacura_kallisti/plugins/__init__.py
abacura-kallisti/abacura_kallisti/screens.py
abacura-kallisti/abacura_kallisti/widgets/_lokmap.py

Removed serum, with a couple hacks for now

---

abacura-core/abacura/mud/session.py
abacura-core/abacura/plugins/aliases/helper.py
abacura-core/abacura/plugins/commands/__init__.py
abacura-core/abacura/plugins/commands/command_helper.py
abacura-core/abacura/plugins/commands/workers.py
abacura-core/abacura/plugins/debug/profile.py
abacura-core/abacura/plugins/debug/pycharm.py
abacura-core/abacura/plugins/events/events.py
abacura-core/abacura/plugins/exec/PythonExecutor.py
abacura-core/abacura/plugins/session/helper.py
abacura-core/abacura/plugins/task_queue/runner.py
abacura-core/abacura/plugins/tickers/helper.py
abacura-kallisti/abacura_kallisti/plugins/atlas/WorldController.py
abacura-kallisti/abacura_kallisti/plugins/atlas/location_helper.py
abacura-kallisti/abacura_kallisti/plugins/atlas/room_watcher.py
abacura-kallisti/abacura_kallisti/plugins/atlas/travel_helper.py
abacura-kallisti/abacura_kallisti/plugins/autobuf.py
abacura-kallisti/abacura_kallisti/plugins/lok.py
abacura-kallisti/abacura_kallisti/plugins/lokcomms.py
abacura-kallisti/abacura_kallisti/plugins/msdp/msdp_controller.py
abacura-kallisti/abacura_kallisti/plugins/odometer/odometer.py
abacura-kallisti/abacura_kallisti/plugins/scripts/tour_demo.py
abacura-kallisti/abacura_kallisti/plugins/zones/telluria.py
abacura-kallisti/abacura_kallisti/plugins/zones/xendorian.py

Improve format of command help and show default values

Updated help for all #commands

---

abacura-core/abacura/mud/session.py
abacura-core/abacura/plugins/commands/command_helper.py
abacura-kallisti/abacura_kallisti/mud/skills.py
abacura-kallisti/abacura_kallisti/plugins/autobuf.py

Simplified autobuff, don't actually need style_row()

Updated #session to use AbacuraPanel + tabulate

---

abacura-core/abacura/mud/session.py
abacura-core/abacura/plugins/actions/helper.py
abacura-core/abacura/plugins/debug/plugin_helper.py
abacura-core/abacura/plugins/sound.py
abacura-core/abacura/plugins/tickers/helper.py
abacura-kallisti/abacura_kallisti/atlas/tour_guide.py
abacura-kallisti/abacura_kallisti/plugins/__init__.py
abacura-kallisti/abacura_kallisti/plugins/atlas/AreaController.py
abacura-kallisti/abacura_kallisti/plugins/atlas/WorldController.py
abacura-kallisti/abacura_kallisti/plugins/atlas/room_watcher.py
abacura-kallisti/abacura_kallisti/plugins/atlas/travel_helper.py
abacura-kallisti/abacura_kallisti/plugins/odometer/odometer.py
abacura-kallisti/abacura_kallisti/plugins/scripts/tour_demo.py

Increased priority of room watcher prompt event to ensure it updates self.room before other plugins fire 
Added #action command to show registered actions
More output cleanup/fixes
Fix command count in #plugin
Show warning/error panels in several places that were showing orange/red text 
Fixed help for #exit command

Output Cleanup, #action, minor fixex

---

abacura-core/abacura/mud/logger.py
abacura-core/abacura/mud/session.py
abacura-core/abacura/screens/__init__.py
abacura-core/abacura/widgets/footer.py
abacura-kallisti/abacura_kallisti/screens.py

Removed some of the querying for objects where we can use a direct reference

Renamed LOKLog to AbacuraLogger because it's in core

---

abacura-kallisti/abacura_kallisti/atlas/room.py
abacura-kallisti/abacura_kallisti/atlas/travel_guide.py
abacura-kallisti/abacura_kallisti/atlas/world.py
abacura-kallisti/abacura_kallisti/plugins/atlas/travel_helper.py
abacura-kallisti/abacura_kallisti/plugins/scripts/travel.py

Also include a future optimization to avoid looking through "dead-end" areas.  Commented out for further testing.

Fix bug opening hidden doors/gates

---

abacura-core/abacura/mud/session.py
abacura-core/abacura/plugins/__init__.py
abacura-core/abacura/plugins/task_queue/__init__.py
abacura-core/abacura/plugins/task_queue/runner.py
abacura-kallisti/abacura_kallisti/plugins/lok.py
abacura-kallisti/abacura_kallisti/widgets/_loktask_queue.py

Renamed QueueManager to TaskManager
Added a TaskQueue with a function to check for insertability
Show insertability in #q command
Combat queue only inserts if there is an opponent
nco/any/move only insert if there is no opponent
Add properties to make code simpler

Task/Command Queue improvements for insertability check

---

abacura-core/abacura/css/abacura.css
abacura-core/abacura/plugins/session/log_search.py
abacura-core/abacura/screens/__init__.py
abacura-kallisti/abacura_kallisti/css/kallisti.css
abacura-kallisti/abacura_kallisti/plugins/atlas/big_map.py
abacura-kallisti/abacura_kallisti/screens.py

hitting escape will close any open windows within the main screen #map will bring up a map, removed F6

Show a red [ x ] to close windows

---

abacura-core/abacura/css/abacura.css
abacura-core/abacura/plugins/session/log_search.py
abacura-kallisti/abacura_kallisti/atlas/messages.py
abacura-kallisti/abacura_kallisti/plugins/atlas/WorldController.py
abacura-kallisti/abacura_kallisti/widgets/_lokmap.py

Remove close button from log search window

Add 3x3 map, wilderness map types
